# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: move_tree.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="move_tree.proto",
    package="maia",
    syntax="proto2",
    serialized_pb=_b(
        '\n\x0fmove_tree.proto\x12\x04maia"Z\n\x04Game\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\twhite_elo\x18\x02 \x01(\r\x12\x11\n\tblack_elo\x18\x03 \x01(\r\x12\x1b\n\x06\x62oards\x18\x04 \x03(\x0b\x32\x0b.maia.Board"]\n\x05\x42oard\x12\x0b\n\x03\x66\x65n\x18\x01 \x01(\t\x12\x0b\n\x03ply\x18\x02 \x01(\r\x12\x0c\n\x04move\x18\x03 \x01(\t\x12\x12\n\nmove_index\x18\x04 \x01(\x05\x12\x18\n\x04tree\x18\x05 \x01(\x0b\x32\n.maia.Node"m\n\x04Node\x12\r\n\x05\x64\x65pth\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x14\n\x0c\x63hild_values\x18\x03 \x03(\x02\x12\x13\n\x0b\x63hild_moves\x18\x04 \x03(\t\x12\x1c\n\x08\x63hildren\x18\x05 \x03(\x0b\x32\n.maia.Node'
    ),
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_GAME = _descriptor.Descriptor(
    name="Game",
    full_name="maia.Game",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="game_id",
            full_name="maia.Game.game_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="white_elo",
            full_name="maia.Game.white_elo",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="black_elo",
            full_name="maia.Game.black_elo",
            index=2,
            number=3,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="boards",
            full_name="maia.Game.boards",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=115,
)


_BOARD = _descriptor.Descriptor(
    name="Board",
    full_name="maia.Board",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="fen",
            full_name="maia.Board.fen",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="ply",
            full_name="maia.Board.ply",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="move",
            full_name="maia.Board.move",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="move_index",
            full_name="maia.Board.move_index",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="tree",
            full_name="maia.Board.tree",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=117,
    serialized_end=210,
)


_NODE = _descriptor.Descriptor(
    name="Node",
    full_name="maia.Node",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="depth",
            full_name="maia.Node.depth",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="maia.Node.value",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="child_values",
            full_name="maia.Node.child_values",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="child_moves",
            full_name="maia.Node.child_moves",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="children",
            full_name="maia.Node.children",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=212,
    serialized_end=321,
)

_GAME.fields_by_name["boards"].message_type = _BOARD
_BOARD.fields_by_name["tree"].message_type = _NODE
_NODE.fields_by_name["children"].message_type = _NODE
DESCRIPTOR.message_types_by_name["Game"] = _GAME
DESCRIPTOR.message_types_by_name["Board"] = _BOARD
DESCRIPTOR.message_types_by_name["Node"] = _NODE

Game = _reflection.GeneratedProtocolMessageType(
    "Game",
    (_message.Message,),
    dict(
        DESCRIPTOR=_GAME,
        __module__="move_tree_pb2"
        # @@protoc_insertion_point(class_scope:maia.Game)
    ),
)
_sym_db.RegisterMessage(Game)

Board = _reflection.GeneratedProtocolMessageType(
    "Board",
    (_message.Message,),
    dict(
        DESCRIPTOR=_BOARD,
        __module__="move_tree_pb2"
        # @@protoc_insertion_point(class_scope:maia.Board)
    ),
)
_sym_db.RegisterMessage(Board)

Node = _reflection.GeneratedProtocolMessageType(
    "Node",
    (_message.Message,),
    dict(
        DESCRIPTOR=_NODE,
        __module__="move_tree_pb2"
        # @@protoc_insertion_point(class_scope:maia.Node)
    ),
)
_sym_db.RegisterMessage(Node)


# @@protoc_insertion_point(module_scope)
